// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview An AI agent that recommends the next best action for a manager to take with a lead.
 *
 * - generateNextStep - A function that provides a recommendation.
 * - GenerateNextStepInput - The input type for the generateNextStep function.
 * - GenerateNextStepOutput - The return type for the generateNextStep function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';

const GenerateNextStepInputSchema = z.object({
  balance: z.number().describe('The current balance of the user.'),
  totalPnl: z.number().describe('The total profit and loss of the user.'),
  isRunning: z.boolean().describe('Whether the trading robot is currently running.'),
  isHotLead: z.boolean().describe('Whether the user is marked as a hot lead (ready to deposit).'),
  chatHistory: z.string().describe('The entire chat history as a JSON string.'),
  timeLimitReached: z.boolean().describe('Whether the user has reached their demo time limit.'),
});
export type GenerateNextStepInput = z.infer<typeof GenerateNextStepInputSchema>;

const GenerateNextStepOutputSchema = z.object({
  recommendation: z.string().describe('The concise, actionable recommendation for the manager in Russian.'),
  priority: z.enum(['CRITICAL', 'HIGH', 'MEDIUM', 'LOW']).describe('The priority of this action.'),
});
export type GenerateNextStepOutput = z.infer<typeof GenerateNextStepOutputSchema>;

export async function generateNextStep(input: GenerateNextStepInput): Promise<GenerateNextStepOutput> {
  return generateNextStepFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateNextStepPrompt',
  input: { schema: GenerateNextStepInputSchema },
  output: { schema: GenerateNextStepOutputSchema },
  prompt: `You are an expert AI sales coach for a financial trading platform. Your task is to analyze the state of a user (lead) and provide a clear, actionable "next step" recommendation for the sales manager. The recommendation MUST be in Russian.

  Analyze the following user data:
  - Current Balance: {{{balance}}}
  - Total P&L: {{{totalPnl}}}
  - Robot Running: {{{isRunning}}}
  - Is Hot Lead (ready to deposit): {{{isHotLead}}}
  - Demo Time Limit Reached: {{{timeLimitReached}}}
  - Chat History (JSON): {{{chatHistory}}}

  Based on this data, determine the single most important action the manager should take right now.

  **CRITICAL RULES:**

  1.  **HOT LEAD**: If \`isHotLead\` is true, the user has provided contact details and is waiting. This is the highest priority.
      - **Priority**: CRITICAL
      - **Recommendation**: "Лид оставил контакты и ждет! Немедленно свяжитесь, чтобы завершить пополнение."

  2.  **TIME LIMIT REACHED**: If the demo time is up.
      - **Priority**: HIGH
      - **Recommendation**: "Время демо-сессии истекло. Свяжитесь с клиентом, покажите итоговую прибыль и предложите активировать реальный счет."

  3.  **USER ASKING FOR HELP IN CHAT**: Analyze the last message in the chat history. If it's from the user and contains a question or expresses confusion.
      - **Priority**: HIGH
      - **Recommendation**: "Клиент задал вопрос в чате и ждет ответа. Необходимо ответить как можно скорее, чтобы помочь."

  4.  **SIGNIFICANT PROFIT**: If P&L is positive and significant (e.g., > $50).
      - **Priority**: MEDIUM
      - **Recommendation**: "Клиент видит хорошую прибыль. Отличный момент, чтобы написать ему, поздравить и предложить зафиксировать результат, перейдя на реальный счет."

  5.  **TRADING STOPPED**: If the robot is NOT running, but time has NOT run out.
      - **Priority**: MEDIUM
      - **Recommendation**: "Клиент остановил робота. Узнайте, почему. Возможно, у него есть вопросы или сомнения, которые нужно развеять."

  6.  **STAGNANT/NO ACTION**: If the user is not trading and not chatting.
      - **Priority**: LOW
      - **Recommendation**: "Клиент неактивен. Напишите ему, спросите, все ли понятно и нужна ли помощь в выборе робота или запуске."
  
  7.  **DEFAULT**: If none of the above specific conditions are met, provide a general recommendation.
      - **Priority**: LOW
      - **Recommendation**: "Проанализируйте историю сделок и чата, чтобы найти повод для начала диалога. Можно отметить удачную сделку или предложить помощь."


  Your output must be a JSON object with a 'recommendation' and a 'priority'.
  `,
});

const generateNextStepFlow = ai.defineFlow(
  {
    name: 'generateNextStepFlow',
    inputSchema: GenerateNextStepInputSchema,
    outputSchema: GenerateNextStepOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    if (!output) {
      throw new Error("AI failed to generate a next step recommendation.");
    }
    return output;
  }
);
