// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A robot recommendation AI agent.
 *
 * - recommendRobot - A function that handles the robot recommendation process.
 * - RecommendRobotInput - The input type for the recommendRobot function.
 * - RecommendRobotOutput - The return type for the recommendRobot function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendRobotInputSchema = z.object({
  riskTolerance: z
    .string()
    .describe(
      'The users risk tolerance. Can be one of the following: low, medium, high.'
    ),
  investmentGoals: z.string().describe('The investment goals of the user.'),
});
export type RecommendRobotInput = z.infer<typeof RecommendRobotInputSchema>;

const RecommendRobotOutputSchema = z.object({
  robotName: z.string().describe('The name of the recommended robot.'),
  robotDescription: z.string().describe('A short description of the robot.'),
});
export type RecommendRobotOutput = z.infer<typeof RecommendRobotOutputSchema>;

export async function recommendRobot(input: RecommendRobotInput): Promise<RecommendRobotOutput> {
  return recommendRobotFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recommendRobotPrompt',
  input: {schema: RecommendRobotInputSchema},
  output: {schema: RecommendRobotOutputSchema},
  prompt: `You are an AI trading robot recommendation expert.

You will recommend one of the following robots based on the user's risk tolerance and investment goals:

Robots:

1.  "Risk Averse Robot": This robot is designed for users with low risk tolerance. It focuses on preserving capital and generating steady, albeit smaller, returns. It invests in low-volatility assets and avoids high-risk trades.
2.  "Balanced Robot": This robot is suitable for users with a medium risk tolerance. It aims for a balance between capital preservation and growth. It invests in a mix of asset classes and takes on moderate risk.
3.  "High Growth Robot": This robot is designed for users with a high risk tolerance. It seeks to maximize returns, even if it means taking on significant risk. It invests in high-volatility assets and is willing to make aggressive trades.

Risk Tolerance: {{{riskTolerance}}}
Investment Goals: {{{investmentGoals}}}

Based on the information above, which robot do you recommend? What is a short description of the robot? Please respond with the robot name and short description.
`,
});

const recommendRobotFlow = ai.defineFlow(
  {
    name: 'recommendRobotFlow',
    inputSchema: RecommendRobotInputSchema,
    outputSchema: RecommendRobotOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
